# Generated by Django 4.0.5 on 2022-08-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamyon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
