# Generated by Django 4.0.3 on 2022-03-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamyon', '0002_post_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
