# Generated by Django 4.0.5 on 2022-09-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamyon', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
    ]
