# Generated by Django 4.0.5 on 2022-10-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamyon', '0003_remove_comment_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website_url',
        ),
    ]
