# Generated by Django 4.0.3 on 2022-04-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamyon', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-post_date',)},
        ),
    ]
