# Generated by Django 4.0.5 on 2023-07-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamyon', '0004_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='hamyon.ipmodel'),
        ),
    ]
